### ISSUE TITLE
Add nodes for Blackboard operations

### ISSUE THREAD

**Issue by Wichamir** [bitbrain/beehave#132]
### Discussed in #125

Add 4 predefined nodes for `Blackboard` operations:

- `BlackboardSetAction` - sets a key to a specified value
- `BlackboardEraseAction` - erases the key from the blackboard
- `BlackboardHasCondition` - returns `SUCCESS` if the key exists in the blackboard, otherwise `FAILURE`
- `BlackboardCompareCondition` - compares two values from the blackboard by using the specified comparison operator

We can use the built-in `Expression` class to make it possible to define values, which are not a `String`.

**Comment by GeroVeni** [comment]
@Wichamir that timing

**Comment by GeroVeni** [comment]
@Wichamir I think I am going to close my PR in favor of yours :)

**Comment by GeroVeni** [comment]
A first attempt at the icons. The idea was to use the blackboard icon and replace the last column with a symbol depending on the action. I have to say I am not very pleased with the result as the icons are kinda small and not very visible. I tried to keep them the same width that the last column was but maybe that is not the way to go.

Maybe if the icons were bigger and on top of the blackboard icon it would be better ? (Like the star in the SequenceStar node)
Let me know your thoughts.

Also I picked the leaf color, since they are actions, but I was thinking maybe the original utility color would be good too ?

![blackboard_has_condition](https://user-images.githubusercontent.com/9087101/219054653-94de2341-8894-4dd6-88e1-522a7ed1b00e.svg) Blackboard has condition
![blackboard_set_action](https://user-images.githubusercontent.com/9087101/219054661-ad54b0a2-deda-4725-b79b-964482c56256.svg) Blackboard set action
![blackboard_compare_condition](https://user-images.githubusercontent.com/9087101/219054663-f76c9f63-9d18-4023-9d3c-5ac5ae44babf.svg) Blackboard compare condition
![blackboard_erase_action](https://user-images.githubusercontent.com/9087101/219054666-980cde66-0759-4a07-9810-d268cf979bbe.svg) Blackboard erase action
![blackboard_erase_action_2](https://user-images.githubusercontent.com/9087101/219054670-cf08eead-bb63-4076-b039-c3d388528114.svg) Blackboard erase action (alt)

**Comment by bitbrain** [comment]
Thank you @GeroVeni - I really like those designs. In terms of colours, any action should have the action colour to not visually confuse people. While they share the icon design with the `Blackboard` node, they are fundamentally different (so I'd say we should use the leaf color)
