### ISSUE TITLE
Overhaul icons

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/beehave#72]
We are still using the default icons coming [from the original demo project](https://github.com/viniciusgerevini/godot-behavior-tree-example/tree/master/addons/behavior_tree/icons) however, it is time to introduce a consistent icon theme that makes it clear that these are indeed beehave nodes.

@nathanhoad already introduced a new logo:

![logo](https://raw.githubusercontent.com/bitbrain/beehave/godot-4.x/assets/logo.svg)

Having icons in a similar colour theme (and with cute-round corners) is way more fitting than the current ones we have.

**Comment by lostptr** [comment]
I would like to add my two cents since I found some of the icons to be a little confusing:

## Selector
This node will execute the first child and if it fails, it will execute the next one and so on. The current icon ![selector](https://user-images.githubusercontent.com/21160216/207870769-fb16a7b0-c6ec-4237-a62b-b532e28c1682.svg) looks like its repeating something...? I dont think there's an icon that can fully represent what it does but I think the current one is kinda misleading. My suggestion would be something like this ![move_down_FILL1_wght700_GRAD0_opsz24](https://user-images.githubusercontent.com/21160216/207871223-aa5c05ef-9b04-42b2-8786-0b66cc9698d9.svg) [Material Icons - Move Down](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amove_down%3AFILL%401%3Bwght%40700%3BGRAD%400%3Bopsz%4024). 

Another (kinda) related issue: I've seen other implementations naming this node `Fallback` which represents its behaviour much clearer imho ("if this doesn't work, do that").

## Limiter
This node will execute its child `x` amount of times. The current icon ![limiter](https://user-images.githubusercontent.com/21160216/207873859-b9aa5419-40bf-488d-9fe2-34d382d3127a.svg) does not evoke a "repeat" action to me. Maybe something like this ![refresh_FILL1_wght700_GRAD0_opsz24](https://user-images.githubusercontent.com/21160216/207874100-bf144c7a-e850-4d28-bef9-0aa15fa4cd26.svg) [Material Icons - Refresh](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Arefresh%3AFILL%401%3Bwght%40700%3BGRAD%400%3Bopsz%4024) could be better, or even the current icon for the `Selector`.

## Action
Not really a problem with this one, I just find that ![directions_run_FILL1_wght700_GRAD0_opsz24](https://user-images.githubusercontent.com/21160216/207874560-faa594b8-1d7c-4350-a9ee-4dbaba268c23.svg) [Material Icons - Run](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adirections_run%3AFILL%401%3Bwght%40700%3BGRAD%400%3Bopsz%4024) is cooler than the current circle. 😆

Kinda went a little off topic here, if you want I can create an issue for these changes instead.

**Comment by bitbrain** [comment]
@lostptr I really like your suggestions. Yes, the intention of this ticket is to overhaul not only the colour/style but also the visual queue.

**Comment by lostptr** [comment]
These are the new icons I found:

![category_bt](https://user-images.githubusercontent.com/21160216/208312512-f350f770-c947-417e-b382-cc865ae61bc4.svg) **Category BT**
![tree](https://user-images.githubusercontent.com/21160216/208311899-e1bae7c4-739f-4ad2-9f0f-bf0e1a61bc64.svg) **Behaviour Tree**
![blackboard](https://user-images.githubusercontent.com/21160216/208311900-b73dbf2c-bb56-46d3-80ed-616aa17272f4.svg) **Blackboard**


![condition](https://user-images.githubusercontent.com/21160216/208311893-39831540-13b8-4b7e-8a7e-1282cdc42647.svg) **Condition**
![action](https://user-images.githubusercontent.com/21160216/208312132-d3e3557e-41c4-48c6-9b4b-3d41c401b1df.svg) **Action**

![category_decorator](https://user-images.githubusercontent.com/21160216/208312507-4e1b4eb5-03a7-48d9-8185-97f81efeeb3f.svg) **Category Decorator**
![succedeer](https://user-images.githubusercontent.com/21160216/208312105-0a27eac3-31d8-4e47-b6f3-a0b4ffa9de50.svg) **Succedder**
![failer](https://user-images.githubusercontent.com/21160216/208311897-ea73277d-a158-43a4-a39a-90968d6fb79f.svg) **Failer**
![inverter](https://user-images.githubusercontent.com/21160216/208311901-2aec4d7e-0e56-4b60-bad8-ca6ad114ba68.svg) **Inverter**
![repeater](https://user-images.githubusercontent.com/21160216/208311904-b4f76c41-fa36-4d6e-8eba-1542e32aab04.svg) **Repeater**

![category_composite](https://user-images.githubusercontent.com/21160216/208312525-af0be2ce-c4c7-4af1-b7cb-6fef1ee21b80.svg) **Category Composite**
![sequence](https://user-images.githubusercontent.com/21160216/208311895-39f4ebe2-2c18-4266-af9a-2f155cce5899.svg) **Sequence**
![sequence_reactive](https://user-images.githubusercontent.com/21160216/208311902-9a4b1d6c-be02-4ee0-9a3f-9ed2e31372f0.svg) **SequenceReactive**
![selector](https://user-images.githubusercontent.com/21160216/208311894-4d11845a-90c9-42a7-8351-409a0d1d9d8d.svg) **Selector**
![selector_reactive](https://user-images.githubusercontent.com/21160216/208311903-65061c9d-622c-4d3f-9821-8485180828e2.svg) **SelectorReactive**

I am keeping in mind the changes in #46 so I chose to use an asterisk for the reactive versions of the icons. (Though maybe the SelectorReactive is too sutle to notice, maybe I can make it bigger) All of the icons are from [Material Icons](https://fonts.google.com/icons?icon.style=Rounded) and are under an [Apache License](https://www.apache.org/licenses/LICENSE-2.0.html). If there are no objections I can make the change.

**Comment by bitbrain** [comment]
@lostptr I like your ideas, however, one of the goals of this ticket is to also introduce a colour theme to the icons that is recognisable. It should definitely feature this colour [#FFAA01](https://www.colorhexa.com/ffaa01). Another thing I was wondering is if we can [introduce a hexagon shape](https://www.youtube.com/watch?v=thOifuHs6eY), as thematically it would be fitting (bee's live in a _beehave_... uhm, I meant bee hive after all!)

**Comment by lostptr** [comment]
I could come up with this pallete:
![Beehave Palette](https://user-images.githubusercontent.com/21160216/208794870-27ac05a8-37ee-44a6-8959-e58863deeb49.png)

What do you think? (Now that I am looking again, it reminds me of powerpuff girls 😅)
Thay have a nice contrast with the godot background color:
![image](https://user-images.githubusercontent.com/21160216/208795080-29bc0784-866f-46ef-a5e0-594346c0e695.png)
(Thats the size it would show up in the editor, hence the weird pic size)
Also, adding a hex shape to every icon would be too much for my noobie skills and I dont even know if they would be readable. However, I guess we can change the category icons with this hive icon you see in the picture. Or even the behaviour tree icon could be a hive!

**Comment by bitbrain** [comment]
@lostptr I really like it. How do the icons look on white background? As the icons should work both for dark & light theme.

**Comment by lostptr** [comment]
New version with adjusted colors:
![image](https://user-images.githubusercontent.com/21160216/208903292-33f11dd7-e938-4a06-baaf-3af8ce15c39f.png)

Purple: #C689FF
Yellow: #FFB649
Blue: #46C0E1
Green: #40D29F

They are a little better to see in a light background.

**Comment by bitbrain** [comment]
Love this! Feel free to raise a PR!
