### ISSUE TITLE
Random composite task

### ISSUE THREAD

**Issue by d-bucur** [bitbrain/beehave#74]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a node that runs a random child to simulate some non deterministic behaviour (ie. an NPC in an RPG choosing randomly between walking around or talking to another NPC)

An example implementation can be found here:
https://github.com/libgdx/gdx-ai/wiki/Behavior-Trees#random-selector
https://github.com/libgdx/gdx-ai/wiki/Behavior-Trees#random-sequence

**Describe the solution you'd like**
Two new nodes added:
- Random selector: selects one of the children randomly, runs it and the composite returns the same state 
- Random sequence: shuffles children randomly, and executes them in order the same way that sequence would do

Design issues to resolve:
Star nodes variants: Is there a need to support the **star** variants? Should the default behaviour just be the star version as re-entry into a currently running state is expected? I also have some other thoughts on the whole star behaviour that I will post in a separate discussion.
Probabilities: To support non uniform probabilities for children their weights would need to be added somewhere in the new nodes and correspond to existing children. But this is a problem that can be solved in a new release after the uniform model is implemented.

**Describe alternatives you've considered**
You could have a separate script that randomly shuffles the children and you would get the same behaviour as what I am describing. The problem with this is that it's not really plug and play and that it's not so easy to determine when a composite execution has already ended and you need to do a reshuffle for the next execution. And you have to create a child node with a randomness script attached, and I'm not sure if that child would mess up the execution in some way.
An example:
- SelectorNode
|- ShuffleScript: doesn't extend beehave node, but changes order of the children
|- WalkAroundAction
|- TalkAction

Maybe having it as a decorator node for selector and sequence is a better approach? Would only have a single new node, but it would need to change the composite behaviour, and I'm not sure that's possible.

**Additional context**
I can work on implementing this during the holidays if there is an agreement on the design and an interest in merging this feature

**Comment by bitbrain** [comment]
I really like your idea. It could act as a "proxy" node of its children:

It executes a random child (based on a probability) but keeps running that child until said child is completed (its status is the one of the child)
```
RandomComposite (RUNNING)
  |_ Child A (RUNNING) <-- runs over multiple ticks
  |_ Child B
```
When a child succeeds, this node succeeds:
```
RandomComposite (SUCCESS)
  |_ Child A (SUCCESS)
  |_ Child B
```
When a child fails, this node fails:
```
RandomComposite (FAILURE)
  |_ Child A
  |_ Child B (FAILURE)
```
Interruptions are "forwarded" to the currently running child.

## Where to put the probability?

To avoid coupling, the probability could be stored on the `RandomComposite` itself. Based on the amount of child nodes attached to it, it could expose an array of `float` values (each entry representing the child in the hierarchy)

## What happens if I mix multiple `RandomComposite` together?

```
RandomComposite
  |_ RandomComposite
     |_ Child A
     |_ Child B
  |_ Child C
```
In this case I would imagine that its behaviour described above still applies (and it should not break given the rules above).

## Additional notes

We might want to also consider some form of validation (e.g. show a warning in the editor) if the `RandomComposite` only has a single child attached to it. 

Thoughts?

**Comment by d-bucur** [comment]
Where to put the probability:
- That's the only good place I can think for it, but it has the problem that the user can forget to update the probability array when adding or removing nodes, and that might cause issues at runtime. Maybe we can detect this and add some editor warnings if the numbers don't match, similar to how this works (not sure if it is exposed via editor api)
![image](https://user-images.githubusercontent.com/6576777/208192428-2f346c92-1b7d-4801-a507-ddf6135ffd38.png)
Also when having lots of nodes it might not be clear which number matches which node, and even worse when moving them around. 

- The alternative would be to have it somehow in the children, but that is just worse, unless it can be hidden by default.

- Or it could be a decorator specifying the probability, and if there is no decorator, a uniform probability is used by default. But this would create some funky nesting

I would use a weight rather than a probability, as it requirest less editing when changing things. Ie 1, 5, 4 would translate to 1/10, 5/10, 4/10 where 10 is the sum

Agreed that it should keep running the RUNNING node until it finishes, I think that should be default behavior in all composites, as I mentioned in my other discussion. So do you think it should be a single node with just the Star behaviour or both Star and 'normal'?

**Comment by d-bucur** [comment]
And what do you mean by RandomComposite? I'm guessing a single node type that works like a RandomSelectorStar right?

**Comment by lostptr** [comment]
I second this! I had implemented this in a game I made (however, my behaviour tree logic sucked lol). 

I vote for the array of weights solution.  Here's why:
- Adding the propability to the children looks like a anti-pattern and will reduce action reusability (what if I want the same action to have different probabilities in different scenarios?)
- Creating a `Decorator` introduces more nesting and kinda goes beyond the scope of a `Decorator` which is to transform the status code of its child.
- Leaving the weights in the `RandomSelector` will leave all of the randomizing logic in the same node. Thankfully, adding warnings in the editor [is not hard at all](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-configuration-warning).

As for the *Star nodes, I agree that we would only need to create `RandomSelectorStar` and `RandomSequenceStar` because I can't think of a way of doing the other versions, nor I see any need for them.

**Comment by bitbrain** [comment]
> And what do you mean by RandomComposite?

@d-bucur A new node type yes, that offers the random behaviour in a "generic" manner. We can still discuss the name of it, I just picked one based on the title of this discussion.

> As for the *Star nodes, I agree that we would only need to create RandomSelectorStar and RandomSequenceStar because I can't think of a way of doing the other versions, nor I see any need for them.

Ah, I misunderstood this at first: would the idea be that a `RandomSelectorStar` would execute a random child and `RandomSequenceStar` executes all its children but in random order (via random bag algorithm)?

Looking at https://github.com/bitbrain/beehave/discussions/76 we could simplify a lot here, too. I will also think of some sort of "class diagram" to visualise how we could structure things long-term for this addon. We have to define some sort of "rule set" when to create a new node and when it should be just "a toggle" on a node.

**Comment by d-bucur** [comment]
> would the idea be that a RandomSelectorStar would execute a random child and RandomSequenceStar executes all its children but in random order (via random bag algorithm)?

Yes, that's how the gdx-ai library does it, but I say we can just start with the RandomSelector as it's a bit more generic. The only difference between the two is that in the RandomSequnce you are guaranteed to iterate over all the children in random order, while in RandomSelector you could hit the same child multiple times in a row as the events are independent.

> I vote for the array of weights solution

Yes, this is probably the best. Thanks for the link to the warnings API, that's very useful!

**Comment by bitbrain** [comment]
> while in RandomSelector you could hit the same child multiple times

One solution for this is to configure an optional property called something along the lines of "invoke separation" that guarantees that a particular node will not be considered for selection for X selections.

**Comment by d-bucur** [comment]
This is basically the same as the behaviour of RandomSequence. I am starting to lean more into the separate node idea given the other discussion

**Comment by bitbrain** [comment]
I created https://github.com/bitbrain/beehave/issues/77 for us to introduce editor warnings. Feel free to pick it up!

**Comment by lostptr** [comment]
Hey, since I am on the icon hype train, I ended up making the icons for ![sequence_random](https://user-images.githubusercontent.com/21160216/209043256-bcd7b492-669d-4325-baff-6d6d25c7bf2c.svg) `SequenceRandom` and ![selector_random](https://user-images.githubusercontent.com/21160216/209042863-21f18e9b-0c94-46b6-afaf-839e6a926be3.svg) `SelectorRandom`! (its the same but with little dice)

**Comment by bitbrain** [comment]
@lostptr for this node, what if we put even more emphasis on the dice?

Some ideas:

`SequenceRandom`
![1](https://user-images.githubusercontent.com/822035/209087194-8d226652-ab94-4b98-972e-70bd889e42ed.PNG)

`SelectorRandom`
![2](https://user-images.githubusercontent.com/822035/209087196-3aceb083-6698-4ab9-8a81-fb889ea48a1a.PNG)

**Comment by lostptr** [comment]
@bitbrain I agree, you can barely see the dice. I was trying to balance between the base composite and the random factor. However, the bigger the dice, the harder it is to identify the composite node it is based on. The sequence does not look like a list because there's no lines and the selector I would need to make the dice even smaller and harder to read (you can see that I made the dice bigger then the square on top to be readable)

We could ditch the whole Sequence/Selector thing and make something completely different like:
- `SequenceRandom` can have a shuffle icon (like a playlist on spotify)
![image](https://user-images.githubusercontent.com/21160216/209143941-f567b2ec-8ddf-40dc-8e31-b29a59088a7d.png)
- Then we can keep the dice to the `SelectorRandom`:
![image](https://user-images.githubusercontent.com/21160216/209145066-21d8c8b2-7ed5-4bdc-bffa-a4c5a596a68b.png)

**Comment by bitbrain** [comment]
@lostptr one problem with the shuffle icon is that it communicates "inconsistently" that it is a 'random' node. What I liked about the previous versions suggested by you and me is the fact that both icons communicate consistently that it is in fact a "random node" via the dice.

**Comment by lostptr** [comment]
I think now they are looking better:

![selector](https://user-images.githubusercontent.com/21160216/209412875-ea1152ca-d151-41ba-9e54-7259f13001be.svg) `Selector`
![selector_random](https://user-images.githubusercontent.com/21160216/209412879-80a98b58-e67f-4dbc-8c96-429f6b3ff3a1.svg) `SelectorRandom`
![sequence](https://user-images.githubusercontent.com/21160216/209412884-91600a9c-fb0b-4e90-9dbe-8ff86d15ffd2.svg) `Sequence`
![sequence_random](https://user-images.githubusercontent.com/21160216/209413041-efbff8ff-4d1d-405b-8fa5-0907ec9486eb.svg) `SequenceRandom`

Can we add them like this?

**Comment by bitbrain** [comment]
@lostptr I love this!
